# docker-compose.yml
version: '2'
services:
    prometheus:
        container_name: prometheus
        image: prom/prometheus
        volumes:
            - prometheus_data:/prometheus
            - ./prometheus/:/etc/prometheus/
        command:
            - '-config.file=/etc/prometheus/prometheus.yml'
            - '-alertmanager.url=http://alertmanager:9093'
        ports:
            - '9090:9090'
    node-exporter:
        container_name: node
        image: prom/node-exporter
        ports:
            - '9100:9100'
    grafana:
        container_name: grafana
        image: grafana/grafana
        environment:
            - GF_SECURITY_ADMIN_PASSWORD=pass
        volumes:
            - grafana_data:/var/lib/grafana
        depends_on:
            - prometheus
        ports:
            - '3000:3000'
    alertmanager:
        container_name: alertmanager
        image: prom/alertmanager
        command:
             - '-config.file=/alertmanager.yml'
        volumes:
             - ./alertmanager/alertmanager.yml:/alertmanager.yml
        ports:
             - '9093:9093'
#    ssl:
#        image: opencapacity/lets-nginx:1.3
#        environment:
#            - EMAIL=webmaster@opencapacity.co
#            - DOMAIN=test.opencapacity.co
#            - UPSTREAM=grafana:3000
#        ports:
#            - "443:443"
#        volumes:
#            - letsencrypt:/etc/letsencrypt
#            - letsencrypt_backups:/var/lib/letsencrypt
#            - dhparam_cache:/cache
#        depends_on:
#            - grafana
volumes:
    prometheus_data: {}
    grafana_data: {}
#    letsencrypt: {}
#    letsencrypt_backups: {}
#    dhparam_cache: {}
